name: "Custom Role"
assignable_scopes:
  - "/subscriptions/xxx"
  - "/subscriptions/yyy"
permissions:
  actions:
    - "Microsoft.Compute/disks/read"
    - "Microsoft.Compute/disks/write"
  not_actions:
    - "Microsoft.Authorization/*/Delete"
    - "Microsoft.Authorization/*/Write"